version: "3"
services:
  mysqldb:
    container_name: mysql-shop
    image: mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: myShopDB
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test
      MYSQL_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10

  spring-boot-app:
    container_name: spring-online-shop
    image: online-shop.1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18088:8088"
#    environment:
#      MYSQL_HOST: mysql-shop
#      MYSQL_DATABASE: myShopDB
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
#      MYSQL_PORT: 33306    ## we are in same network so_ we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy